language: node_js # Node.js based project
node_js:
  - 12 # Level of Node.js to use
script:
  - touch .nojekyll # Creates a file telling Github not to build the project using Jekyll
deploy:
  provider: pages # Informs Travis this is a deployment to GitHub Pages
  skip_cleanup: true # Prevents Travis from resetting the working directory made during the build
  github_token: $github_token # GitHub access token to use when pushing to the gh-pages branch
  local_dir: / # Directory to push to the gh-pages branch
  on:
    branch: master # Only deploy when the build is on master branch
